### ISSUE TITLE
Distributing tests which are created at runtime

### ISSUE THREAD

**Issue by abhishekbedi1432** [Subito-it/Mendoza#14]
Hi, 
I wanted to ask if this tool in its current state can help with the following:

I am using [XCTGherkin](https://github.com/net-a-porter-mobile/XCTest-Gherkin) to write my UI Tests and some of the test are based on tags I pass on the Launch Arguments (see image attached) and using the [native feature file parsing approach](https://github.com/net-a-porter-mobile/XCTest-Gherkin#native-feature-file-parsing) running tests on the fly.

In such a scenario, will this tool work for parallelization of tests across multiple machines ?

<img width="549" alt="image" src="https://user-images.githubusercontent.com/1243887/184638354-c122aa05-a7cb-4e3c-bcb5-be6b5c4b04a4.png">

**Comment by abhishekbedi1432** [comment]
@tcamin  [XCTGherkin](https://github.com/net-a-porter-mobile/XCTest-Gherkin)  works like [Cucumberish](https://cocoapods.org/pods/Cucumberish) by creating test cases on the fly. In other words, before running the test Xcode doesn't even know which tests to run up until runtime. Did we happen to test this tool for such scenarios?

**Comment by abhishekbedi1432** [comment]
Thanks @tcamin!
Another question though:
I was going through another tool [Marathon](https://github.com/MarathonLabs/marathon) which seems somewhat similar to Mendoza. 

Can you please have a look and share your thoughts?

**Comment by tcamin** [comment]
My advise is to try both tools, assess whether they fit your needs choosing the one that works best. Mendoza does a pretty good job with projects having a standard XCUITests setups, in other scenarios I have little experience.
