### ISSUE TITLE
Multiple swift targets

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/Mendoza#8]
Separating the Mendoza tool into different swift targets i.e Mendoza (executable), MendozaCore (Core functionality), MendozaSharedLibrary and MendozaPlugin this would allow better testability and also use the swift package manager to extent Mendoza

**Comment by tcamin** [comment]
Could you elaborate more why splitting targets would improve testability? What do you mean by 'extent Mendoza'?

Wrt to testing do you think it would be possible to start adding coverage on the target as a whole? Being a thin wrapper around a black box (xcodebuild) what would be your testing strategy?

To give you some context, the project is currently a key tool in the testing pipeline for the CI of our iOS app @ Subito. It is currently working very well and for this reason I'm really cautious when it comes to making significant changes. Add to it that the time to maintain it is currently very low (free time).

**Comment by Ashraf-Ali-aa** [comment]
@tcamin by splitting into multiple targets like Mendoza (executable), MendozaCore (Core functionality) we can use breakpoints on `MendozaCore` etc to help debug issues this was useful when making changes and testing it against the Sandbox project (breakpoints does not work on executable targets). On a side note do you know how we can automatically unlock the keychain or a way to pass in the password to the swift keychain library, the reason I ask was that when running the tool in Xcode via XCTest the `Mendoza` executable file is regenerated as a result we need to keep unlocking the keychain for the Mendoza to access the data.

On the forked project, there are some tests I have written in xctest so that I can validate the changes using the sample project manually, but there is no reason why we can not validate the output from the tool. I currently have two types of tests one way is running the executable file in XCTest and the other way is to call the `Test` class directly with the relevant arguments to debug the tool. I am aware making major changes might break the tool, but with multiple swift targets, we can test individual methods. I am currently using Mendoza within my current organisation for the CI pipeline and I am planning on adding support for 3rd device labs but before I do that I want to add tests to make sure the tool works as expected. 

I am looking at https://github.com/avito-tech/Emcee  to see how we can implement some tests and how we can improve the Mendoza tool

**Comment by tcamin** [comment]
> we can use breakpoints on MendozaCore etc to help debug issues 

I can normally place breakpoints in the Mendoza project with no problems.

> On a side note do you know how we can automatically unlock the keychain or a way to pass in the password to the swift keychain library,

You need to sign the executable with a valid DeveloperID. You'll be asked just once to unlock the keychain
